Output media/install-nerd-font.gif
Set Theme "nord-light"
Set Margin 20
Set Padding 10
Set MarginFill "#b48ead"
Set BorderRadius 5
Set WindowBar ColorfulRight
Set Shell "bash"
Set FontSize 14
Set Width 1300
Set Height 600
Set TypingSpeed 80ms
Set WaitTimeout 30s
Set Framerate 6

Source media/scenes/01-explore.tape
Source media/scenes/02-interactive.tape
Source media/scenes/03-quiet-interactive.tape
Source media/scenes/04-batch.tape
